### ISSUE TITLE
no se pueden levantar los datos guardados por el programa

### ISSUE THREAD

**Issue by yagui** [ferchaure/bci#10]
Si se registra con la fpga se obtiene el error

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ariel/Documents/Facultad/Doctorado/repos/bmi-gui/capture.py", line 34, in get_data_from_file
    Parser =  getattr(import_module("Parsers."+CONFIG["FORMAT"]),"Parser")
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ariel/Documents/Facultad/Doctorado/repos/bmi-gui/Parsers/example_raw.py", line 10, in <module>
    LARGO_TRAMA = (int(CONFIG_PARSER["FORMAT_CONFIG"]["no_tet_ch"]) + CONFIG['#CHANNELS'] ) * int(CONFIG_PARSER["FORMAT_CONFIG"]["byte4sample"])
KeyError: 'no_tet_ch'

si se guarda del mismo archivo de prueba que viene con el soft

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ariel/Documents/Facultad/Doctorado/repos/bmi-gui/capture.py", line 37, in get_data_from_file
    parser = Parser(cola,logging,data_in)
  File "/home/ariel/Documents/Facultad/Doctorado/repos/bmi-gui/Parsers/example_raw.py", line 21, in __init__
    self.file_input = open(file_input_name,'rb')
IOError: [Errno 2] No such file or directory: '/home/ariel/bci_registros/a/data_test'

**Comment by ferchaure** [comment]
Parece que habia empezado a replantearme cosas, lo que habria que resolver es lo siguiente; se guarda todo tal cual se obtiene (trama entera y mas pesada) o ya parseados (solo la señal de los canales)?. Ahora esta guardando solo los canales pero que pasaría si la fpga detecta spikes?

**Comment by yagui** [comment]
yo diria que primero se resuelva el bug de que no se pueden levantar los datos, y mas adelante abrimos nuevos issues para discutir esos dos problemas distintos (como manejar la detección de spikes y la pérdida de datos). En ese sentido, si se puede guardar el dato crudo como viene de la fpga, pero en general todos los software que vi almacenan destripados de cualquier otra información que no sea registros así que se podría almacenar los datos ya parseados, en 16 bits, complemento a 2.

**Comment by ferchaure** [comment]
otra pregunta relacionada, sigo el esquema viejo de tener que concatenar los archivos antes o hago que el propio código en python vaya buscando el próximo segmento?

**Comment by yagui** [comment]
no entiendo la pregunta. Que significa concatenar "antes". No es el "propio código en python" el que va tomando de a un archivo? Necesito aclaraciones :-P

**Comment by ferchaure** [comment]
Hasta ahora leen todo un archivo, no van buscando el siguiente. En parte xq sino obligas al usuario a fumarse todo el archivo para revisar algo. una opción en agregar parámetros para levantar archivos que incluyan tiempo de inicio y final. En cualquier caso voy a hacer uno que lea lo que se guarda sin mas intervención del usuario y dsp discutimos.
